# Site settings
title: Pragmatic Technology
author: John Watson
email: john@pragmatictech.guru
description: > # this means to ignore newlines until "baseurl:"
  Exploring agile delivery by adapting software designs to
  embrace the "dev" in DevOps. Blending open source software
  and tools in a corporate enterprise world.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.pragmatictech.guru" # the base hostname & protocol for your site

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://github.com/jwatson3d/jwatson3d.github.io/raw/master/img/JW-avatar.png

permalink: pretty
#permalink: /blog/:title

twitter_username: jwatson3d
github_username:  jwatson3d
linkedin_username: jwatson3d

# The release of Jekyll Now that you're using
version: v3.4.5

# Build settings
markdown: kramdown

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules